- name: variable retrive from file
  hosts: local
  vars_files:
  - variables.yaml
  tasks:
  - name: check variable
    ansible.builtin.debug:
      msg: "Myself {{Name}} , I am {{Role}} , I am Practicing {{Task}}"