- name: conditions
  hosts: localhost
  become: yes
  tasks:
    - name: check hari user exist or not
      ansible.builtin.command: id hari 
      register: user 
      ignore_errors: true
    
    - name: print user info
      ansible.builtin.debug:
          msg: "{{user.rc}}"
    
    - name: create user if not exist
      ansible.builtin.user:
        name: hari 
      when: user.rc != 0
